package com.school.student.mapper;

import com.school.student.domain.entity.Student;
import com.school.student.domain.entity.StudentStatus;
import com.school.student.dto.request.StudentRequest;
import com.school.student.dto.request.StudentUpdateRequest;
import com.school.student.dto.response.StudentResponse;
import org.mapstruct.*;

/**
 * Student Mapper
 *
 * MapStruct mapper for converting between Student entity and DTOs.
 * Automatically generates implementation at compile time.
 *
 * CRITICAL (D-002): ALL DTO mapping MUST use MapStruct.
 * NO manual mapping is allowed.
 */
@Mapper(
    componentModel = "spring",
    unmappedTargetPolicy = ReportingPolicy.IGNORE,
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
public interface StudentMapper {

    // ==================== Request DTO → Entity ====================

    /**
     * Map StudentRequest to Student entity for creation
     *
     * Ignores:
     * - id (generated by database)
     * - studentId (generated by business logic)
     * - status (defaults to ACTIVE)
     * - version (managed by JPA)
     * - audit fields (managed by JPA)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "studentId", ignore = true)
    @Mapping(target = "status", constant = "ACTIVE")
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    Student toEntity(StudentRequest request);

    // ==================== Entity → Response DTO ====================

    /**
     * Map Student entity to StudentResponse DTO
     *
     * Exposes studentId as the business key
     * (NOT the internal database id)
     */
    StudentResponse toResponse(Student entity);

    // ==================== Update Entity from Request ====================

    /**
     * Update Student entity from StudentUpdateRequest
     *
     * BR-STU-007: Only allows updating editable fields:
     * - firstName
     * - lastName
     * - mobile
     * - status
     *
     * All other fields are immutable and ignored.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "studentId", ignore = true)
    @Mapping(target = "dateOfBirth", ignore = true)
    @Mapping(target = "aadhaarNumber", ignore = true)
    @Mapping(target = "email", ignore = true)
    @Mapping(target = "guardianName", ignore = true)
    @Mapping(target = "motherName", ignore = true)
    @Mapping(target = "address", ignore = true)
    @Mapping(target = "identificationMarks", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateEntityFromRequest(
        StudentUpdateRequest request,
        @MappingTarget Student entity
    );
}
