package com.school.configuration.domain.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Configuration Entity - Domain Model
 *
 * Represents a system configuration setting.
 * Configurations are key-value pairs organized by category.
 *
 * Business Rules:
 * - BR-CFG-001: Category + Key combination must be unique
 * - BR-CFG-002: Key must be uppercase with underscores only
 * - BR-CFG-003: Encrypted values stored for sensitive configurations
 *
 * @see ConfigCategory
 * @see DataType
 */
@Entity
@Table(
    name = "configurations",
    uniqueConstraints = {
        @UniqueConstraint(
            name = "uk_category_key",
            columnNames = {"category", "key"}
        )
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Configuration {

    /**
     * Primary key (internal database ID)
     * Generated by database using BIGSERIAL (LESSON-001: Use BIGSERIAL for Long IDs)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Configuration category
     * Groups related configurations together
     * Example: GENERAL, ACADEMIC, FINANCIAL, SYSTEM
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "category", nullable = false, length = 20)
    private ConfigCategory category;

    /**
     * Configuration key (business key)
     * Format: UPPERCASE_WITH_UNDERSCORES
     * Example: SCHOOL_NAME, MAX_UPLOAD_SIZE, DEFAULT_CURRENCY
     *
     * Combined with category, forms unique identifier
     */
    @Column(name = "key", nullable = false, length = 100)
    private String key;

    /**
     * Configuration value
     * Stored as text, interpreted based on dataType
     */
    @Column(name = "value", nullable = false, columnDefinition = "TEXT")
    private String value;

    /**
     * Human-readable description
     * Explains the purpose and usage of this configuration
     */
    @Column(name = "description", length = 500)
    private String description;

    /**
     * Data type of the value
     * Used for type validation and parsing
     * Default: STRING
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "data_type", nullable = false, length = 20)
    @Builder.Default
    private DataType dataType = DataType.STRING;

    /**
     * Encryption flag
     * If true, value contains encrypted data
     * Used for sensitive configurations (passwords, API keys)
     */
    @Column(name = "is_encrypted", nullable = false)
    @Builder.Default
    private Boolean isEncrypted = false;

    // ==================== Optimistic Locking (D-003) ====================

    /**
     * Version field for optimistic locking
     * Prevents concurrent modification conflicts
     * MANDATORY per Global Directive D-003
     */
    @Version
    @Column(name = "version", nullable = false)
    private Integer version;

    // ==================== Audit Fields ====================

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    // ==================== Business Logic ====================

    /**
     * Get the composite key (category + key)
     * Used for logging and cache keys
     */
    public String getCompositeKey() {
        return category.name() + ":" + key;
    }

    /**
     * Check if this is a sensitive configuration
     */
    public boolean isSensitive() {
        return isEncrypted != null && isEncrypted;
    }

    /**
     * Validate key format
     * Must be uppercase with underscores only (no spaces, no special chars)
     */
    public boolean hasValidKeyFormat() {
        if (key == null) {
            return false;
        }
        return key.matches("^[A-Z0-9_]+$");
    }
}
