-- ======================================
-- School Management System - Database Schema
-- Version: 1.0
-- Date: 2026-01-08
-- Description: Complete PostgreSQL DDL for Student and Configuration modules
-- Scope: Students table, Configuration Settings table
-- Constraints: Tables, PKs, FKs, CHECK constraints only
-- Excluded: Indexes, Triggers, Stored Functions (per constraints)
-- ======================================

-- Clean slate: Drop tables if they exist
DROP TABLE IF EXISTS configuration_settings CASCADE;
DROP TABLE IF EXISTS students CASCADE;

-- ======================================
-- STUDENT SERVICE DATABASE (studentdb)
-- ======================================

-- Students Table
CREATE TABLE students (
    -- Primary Key
    id                    BIGSERIAL PRIMARY KEY,

    -- Business Identifier (Auto-generated by application layer)
    student_id            VARCHAR(20) NOT NULL UNIQUE,

    -- Personal Information
    first_name            VARCHAR(50) NOT NULL,
    last_name             VARCHAR(50) NOT NULL,
    date_of_birth         DATE NOT NULL,
    age                   INTEGER NOT NULL,
    adhaar_number         VARCHAR(12) NOT NULL UNIQUE,
    address               VARCHAR(500) NOT NULL,
    identification_marks  VARCHAR(200),

    -- Guardian Information
    guardian_name         VARCHAR(100) NOT NULL,
    mother_name           VARCHAR(100) NOT NULL,

    -- Contact Information
    phone                 VARCHAR(10) NOT NULL UNIQUE,
    email                 VARCHAR(100) NOT NULL UNIQUE,

    -- Status
    status                VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    -- Audit Fields
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Optimistic Locking
    version               INTEGER NOT NULL DEFAULT 0,

    -- Constraints
    CONSTRAINT chk_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_age CHECK (age >= 3 AND age <= 18),
    CONSTRAINT chk_adhaar_format CHECK (adhaar_number ~ '^\d{12}$'),
    CONSTRAINT chk_phone_format CHECK (phone ~ '^\d{10}$'),
    CONSTRAINT chk_email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'),
    CONSTRAINT chk_dob_not_future CHECK (date_of_birth <= CURRENT_DATE)
);

-- Table Comments
COMMENT ON TABLE students IS 'Student registration and profile information';
COMMENT ON COLUMN students.student_id IS 'Auto-generated student ID in format STU-YYYY-NNNNN';
COMMENT ON COLUMN students.age IS 'Calculated from date_of_birth, must be 3-18 at registration';
COMMENT ON COLUMN students.adhaar_number IS 'Indian national ID, 12 digits, unique';
COMMENT ON COLUMN students.status IS 'Student status: ACTIVE or INACTIVE';
COMMENT ON COLUMN students.version IS 'Optimistic locking version, incremented on each update';

-- ======================================
-- CONFIGURATION SERVICE DATABASE (configdb)
-- ======================================

-- Configuration Settings Table
CREATE TABLE configuration_settings (
    -- Primary Key
    id              BIGSERIAL PRIMARY KEY,

    -- Configuration Data
    category        VARCHAR(20) NOT NULL,
    key             VARCHAR(100) NOT NULL,
    value           VARCHAR(1000) NOT NULL,
    description     VARCHAR(500),

    -- Audit Fields
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Optimistic Locking
    version         INTEGER NOT NULL DEFAULT 0,

    -- Constraints
    CONSTRAINT chk_category CHECK (category IN ('GENERAL', 'ACADEMIC', 'FINANCE', 'SYSTEM')),
    CONSTRAINT uk_category_key UNIQUE (category, key)
);

-- Table Comments
COMMENT ON TABLE configuration_settings IS 'School-wide configuration key-value pairs';
COMMENT ON COLUMN configuration_settings.category IS 'Configuration category: GENERAL, ACADEMIC, FINANCE, SYSTEM';
COMMENT ON COLUMN configuration_settings.key IS 'Configuration key, unique within category';
COMMENT ON COLUMN configuration_settings.value IS 'Configuration value, max 1000 characters';
COMMENT ON CONSTRAINT uk_category_key ON configuration_settings IS 'Key must be unique within category';

-- ======================================
-- SAMPLE DATA (Optional - for initial setup)
-- ======================================

-- General Settings
INSERT INTO configuration_settings (category, key, value, description) VALUES
('GENERAL', 'SCHOOL_NAME', 'St. Mary''s High School', 'Official school name'),
('GENERAL', 'SCHOOL_CODE', 'SMHS-2026', 'Unique school identifier'),
('GENERAL', 'SCHOOL_ADDRESS', '123 Main Street, City, State - 123456', 'School address'),
('GENERAL', 'CONTACT_EMAIL', 'info@stmarys.edu', 'Primary contact email'),
('GENERAL', 'CONTACT_PHONE', '1234567890', 'Primary contact phone');

-- Academic Settings
INSERT INTO configuration_settings (category, key, value, description) VALUES
('ACADEMIC', 'ACADEMIC_YEAR', '2025-2026', 'Current academic year'),
('ACADEMIC', 'MIN_STUDENT_AGE', '3', 'Minimum student age for registration'),
('ACADEMIC', 'MAX_STUDENT_AGE', '18', 'Maximum student age for registration'),
('ACADEMIC', 'CLASS_CAPACITY', '40', 'Maximum students per class');

-- Finance Settings
INSERT INTO configuration_settings (category, key, value, description) VALUES
('FINANCE', 'CURRENCY', 'INR', 'Currency code'),
('FINANCE', 'REGISTRATION_FEE', '1000', 'Student registration fee');

-- System Settings
INSERT INTO configuration_settings (category, key, value, description) VALUES
('SYSTEM', 'CACHE_TTL_STUDENTS', '7200', 'Student cache TTL in seconds (2 hours)'),
('SYSTEM', 'CACHE_TTL_CONFIG', '14400', 'Config cache TTL in seconds (4 hours)'),
('SYSTEM', 'MAX_SEARCH_RESULTS', '100', 'Maximum search results to return');

-- ======================================
-- VERIFICATION QUERIES
-- ======================================

-- Verify students table structure
-- SELECT column_name, data_type, character_maximum_length, is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'students'
-- ORDER BY ordinal_position;

-- Verify configuration_settings table structure
-- SELECT column_name, data_type, character_maximum_length, is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'configuration_settings'
-- ORDER BY ordinal_position;

-- Verify constraints
-- SELECT constraint_name, constraint_type
-- FROM information_schema.table_constraints
-- WHERE table_name IN ('students', 'configuration_settings');

-- ======================================
-- END OF SCHEMA
-- ======================================
