package com.school.configuration.mapper;

import com.school.configuration.domain.entity.Configuration;
import com.school.configuration.dto.request.ConfigurationRequest;
import com.school.configuration.dto.response.ConfigurationResponse;
import org.mapstruct.*;

/**
 * Configuration Mapper
 *
 * MapStruct mapper for converting between Configuration entity and DTOs.
 * Automatically generates implementation at compile time.
 *
 * CRITICAL (D-002): ALL DTO mapping MUST use MapStruct.
 * NO manual mapping is allowed.
 */
@Mapper(
    componentModel = "spring",
    unmappedTargetPolicy = ReportingPolicy.IGNORE,
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
public interface ConfigurationMapper {

    // ==================== Request DTO → Entity ====================

    /**
     * Map ConfigurationRequest to Configuration entity for creation
     *
     * Ignores:
     * - id (generated by database)
     * - version (managed by JPA for new entities)
     * - audit fields (managed by JPA)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    Configuration toEntity(ConfigurationRequest request);

    // ==================== Entity → Response DTO ====================

    /**
     * Map Configuration entity to ConfigurationResponse DTO
     *
     * Exposes all fields including audit timestamps
     */
    ConfigurationResponse toResponse(Configuration entity);

    // ==================== Update Entity from Request ====================

    /**
     * Update Configuration entity from ConfigurationRequest
     *
     * Updates all fields except:
     * - id (immutable)
     * - audit fields (managed by JPA)
     *
     * Note: Unlike Student Service, Configuration allows updating
     * category and key (composite business key can change).
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateEntityFromRequest(
        ConfigurationRequest request,
        @MappingTarget Configuration entity
    );
}
